- name: Deploy .NET application to EC2
  hosts: all
  become: true

  tasks:
    - name: Install .NET Runtime 8
      apt:
        name: dotnet-runtime-8.0
        state: present
        update_cache: yes