- name: Deploy .NET application to EC2
  hosts: all
  become: true

  tasks:
    - name: Install .NET Runtime 8
      apt:
        name: dotnet-runtime-8.0
        state: present
        update_cache: yes

    - name: Create deployment directory
      ansible.builtin.file:
        path: /var/www/dotnet_app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
  
    - name: Copy application files
      ansible.builtin.copy:
        src: /home/runner/work/Back-End_Challenge_20210221/Back-End_Challenge_20210221/publish/
        dest: /var/www/dotnet_app/
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Set environment variables
      ansible.builtin.copy:
        content: ASPNETCORE_ENVIRONMENT=Development
        dest: /etc/environment
        mode: 0644

    - name: Start .NET application
      ansible.builtin.command: nohup dotnet /var/www/dotnet_app/Back-End_Challenge_20210221.dll >nohup.out 2>nohup.err &
      args:
        chdir: /var/www/dotnet_app/    